c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:
  - 2.17                       # [linux and x86_64]
  - 2.17                       # [linux and not x86_64]
  - 10.13                      # [osx and x86_64]
  - 10.13                      # [osx and arm64]